# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Differ < Formula
  desc "Terminal-native review interface for Git changes"
  homepage "https://github.com/jansmrcka/differ"
  version "1.8.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.8.1/differ_darwin_amd64.tar.gz"
      sha256 "c70a37e42dbf28dea4a75ffe4a37a8704ed85c22587df5b7f0e464b1221c2fef"

      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.8.1/differ_darwin_arm64.tar.gz"
      sha256 "f99949599b9991bffb187377dec8724bb105037c862f6a5eac962fcc7d74a6c9"

      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.8.1/differ_linux_amd64.tar.gz"
      sha256 "4aef0a1ec1199f90c7fe4633ebe883ca3980089bd9cc63ff767e79f2d983aefa"
      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.8.1/differ_linux_arm64.tar.gz"
      sha256 "fba70afbffc2def6e93a08a612ae7dbf56c2370fb1d7ffbea9cd5a6812b16696"
      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  test do
    system "#{bin}/differ", "--version"
  end
end
