# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Differ < Formula
  desc "Terminal UI git diff viewer"
  homepage "https://github.com/jansmrcka/differ"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.3.0/differ_darwin_amd64.tar.gz"
      sha256 "a73044f818bffc154cbcb78fcfc8a306978cdd590c89e6c18f75d0c65ba3dbd0"

      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.3.0/differ_darwin_arm64.tar.gz"
      sha256 "23244fdb2ab060dcf8282a3ac3904b1192dc926e35d0736643685167b4f67111"

      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.3.0/differ_linux_amd64.tar.gz"
      sha256 "3b4a31b841acc49dc1069491e25507b138e5c06593409601d224e1e4ca8cf656"
      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.3.0/differ_linux_arm64.tar.gz"
      sha256 "72b79e73995f1793b826eefc43e807940b0c505939b25fb3c9186920eb047a34"
      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  test do
    system "#{bin}/differ", "--version"
  end
end
