# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Differ < Formula
  desc "Terminal UI git diff viewer"
  homepage "https://github.com/jansmrcka/differ"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.2.0/differ_darwin_amd64.tar.gz"
      sha256 "6afcbc80a06bce7851d8482ef62cfb8bc5374b32249c0cf4832eb758e0ee93f2"

      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.2.0/differ_darwin_arm64.tar.gz"
      sha256 "0217b35ee3214411c9e06251f636a915b4f0a69a31ba94fcc9101f8e79f7e5b7"

      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.2.0/differ_linux_amd64.tar.gz"
      sha256 "4b01f332b86dd68845ef22fc6ea68b3c3d964860965d659d9c4aed1cdc4a7f68"
      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JanSmrcka/differ/releases/download/v1.2.0/differ_linux_arm64.tar.gz"
      sha256 "7214df6cfca87d505ac551e2d437200c6bf52ec068fbc040c60736422bdbde5e"
      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  test do
    system "#{bin}/differ", "--version"
  end
end
